Repository you-can-cook/Gobong, pull requests merged in 2023-08, with the labels that each got.

#4 feat: change from email to oauthId, add oAuthProvider in user entity
  backend/src/main/java/org/youcancook/gobong/domain/user/entity/OAuthProvider.java
  backend/src/main/java/org/youcancook/gobong/domain/user/entity/User.java
Labels: 기능구현 🛫

#5 feat: 평점 서비스 구현 및 테스트 작성
  backend/src/main/java/org/youcancook/gobong/domain/rating/dto/request/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/rating/dto/request/RateRecipeRequest.java
  backend/src/main/java/org/youcancook/gobong/domain/rating/dto/response/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/rating/dto/response/RateRecipeResponse.java
  backend/src/main/java/org/youcancook/gobong/domain/rating/entity/Rating.java
  backend/src/main/java/org/youcancook/gobong/domain/rating/exception/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/rating/exception/IllegalRatingException.java
  backend/src/main/java/org/youcancook/gobong/domain/rating/exception/RatingNotFoundException.java
  backend/src/main/java/org/youcancook/gobong/domain/rating/repository/RatingRepository.java
  backend/src/main/java/org/youcancook/gobong/domain/rating/service/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/rating/service/RatingService.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/entity/Recipe.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/exception/RecipeNotFoundException.java
  backend/src/main/java/org/youcancook/gobong/domain/recipedetail/exception/RecipeDetailNotFoundException.java
  backend/src/main/java/org/youcancook/gobong/domain/user/exception/UserNotFoundException.java
  backend/src/main/java/org/youcancook/gobong/global/error/ErrorCode.java
  backend/src/main/java/org/youcancook/gobong/global/error/exception/IllegalException.java
  backend/src/test/java/org/youcancook/gobong/domain/rating/entity/RatingTest.java
  backend/src/test/java/org/youcancook/gobong/domain/rating/service/RatingServiceTest.java
Labels: 기능구현 🛫

#8 feat: Github Actions CI 스크립트 작성
  .github/workflows/backend-ci.yml
Labels: 인프라 🌎

#10 feat: Github Actions를 활용한 Docker CD(배포) 스크립트 작성
  .github/workflows/backend-cd.yml
  .github/workflows/backend-ci.yml
  backend/Dockerfile
  backend/build.gradle
  backend/docker-compose.yml
Labels: 인프라 🌎

#9 feat: 로그인, 회원가입 보안을 위한 TemporaryToken 도메인 생성
  backend/src/main/java/org/youcancook/gobong/domain/authentication/entity/TemporaryToken.java
  backend/src/main/java/org/youcancook/gobong/domain/authentication/exception/TemporaryTokenFoundException.java
  backend/src/main/java/org/youcancook/gobong/domain/authentication/repository/TemporaryTokenRepository.java
  backend/src/main/java/org/youcancook/gobong/domain/authentication/service/TemporaryTokenService.java
  backend/src/main/java/org/youcancook/gobong/global/config/.gitkeep
  backend/src/main/java/org/youcancook/gobong/global/error/ErrorCode.java
  backend/src/main/java/org/youcancook/gobong/global/util/.gitkeep
  backend/src/main/java/org/youcancook/gobong/global/util/clock/ClockService.java
  backend/src/main/java/org/youcancook/gobong/global/util/clock/DefaultClockService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/org/youcancook/gobong/domain/authentication/service/TemporaryTokenServiceTest.java
Labels: 기능구현 🛫

#12 feat: 레시피 북마크 서비스 구현
  backend/src/main/java/org/youcancook/gobong/domain/bookmarkrecipe/dto/request/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/bookmarkrecipe/dto/request/AddBookmarkRecipeRequest.java
  backend/src/main/java/org/youcancook/gobong/domain/bookmarkrecipe/dto/request/RemoveBookmarkRecipeRequest.java
  backend/src/main/java/org/youcancook/gobong/domain/bookmarkrecipe/dto/response/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/bookmarkrecipe/dto/response/AddBookmarkResponse.java
  backend/src/main/java/org/youcancook/gobong/domain/bookmarkrecipe/entity/BookmarkRecipe.java
  backend/src/main/java/org/youcancook/gobong/domain/bookmarkrecipe/exception/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/bookmarkrecipe/exception/AlreadyBookmarkedRecipeException.java
  backend/src/main/java/org/youcancook/gobong/domain/bookmarkrecipe/exception/BookmarkRecipeNotFoundException.java
  backend/src/main/java/org/youcancook/gobong/domain/bookmarkrecipe/repository/BookmarkRecipeRepository.java
  backend/src/main/java/org/youcancook/gobong/domain/bookmarkrecipe/service/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/bookmarkrecipe/service/BookmarkRecipeService.java
  backend/src/main/java/org/youcancook/gobong/global/error/ErrorCode.java
  backend/src/test/java/org/youcancook/gobong/domain/bookmarkrecipe/service/BookmarkRecipeServiceTest.java
Labels: 기능구현 🛫

#11 feat: token manager 클래스 생성
  backend/build.gradle
  backend/src/main/java/org/youcancook/gobong/domain/authentication/service/TemporaryTokenService.java
  backend/src/main/java/org/youcancook/gobong/global/util/clock/ClockService.java
  backend/src/main/java/org/youcancook/gobong/global/util/clock/DefaultClockService.java
  backend/src/main/java/org/youcancook/gobong/global/util/token/TokenDto.java
  backend/src/main/java/org/youcancook/gobong/global/util/token/TokenManager.java
  backend/src/main/java/org/youcancook/gobong/global/util/token/TokenType.java
  backend/src/main/resources/application.yml
  backend/src/test/java/org/youcancook/gobong/domain/authentication/service/TemporaryTokenServiceTest.java
  backend/src/test/java/org/youcancook/gobong/global/util/token/TokenManagerTest.java
Labels: 기능구현 🛫

#14 feat: 레시피 추가, 업데이트 기능 구현
  backend/src/main/java/org/youcancook/gobong/domain/recipe/dto/request/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/recipe/dto/request/CreateRecipeRequest.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/dto/request/UpdateRecipeRequest.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/dto/response/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/recipe/dto/response/CreateRecipeResponse.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/entity/Difficulty.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/entity/Recipe.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/exception/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/recipe/exception/IllegalDifficultyDescriptionException.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/exception/RecipeAccessDeniedException.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/service/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/recipe/service/RecipeService.java
  backend/src/main/java/org/youcancook/gobong/domain/recipedetail/dto/request/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/recipedetail/dto/request/UploadRecipeDetailRequest.java
  backend/src/main/java/org/youcancook/gobong/domain/recipedetail/repository/RecipeDetailRepository.java
  backend/src/main/java/org/youcancook/gobong/global/error/ErrorCode.java
  backend/src/main/java/org/youcancook/gobong/global/util/clock/bitwise/Bitwise.java
  backend/src/test/java/org/youcancook/gobong/domain/bookmarkrecipe/service/BookmarkRecipeServiceTest.java
  backend/src/test/java/org/youcancook/gobong/domain/rating/service/RatingServiceTest.java
  backend/src/test/java/org/youcancook/gobong/domain/recipe/entity/RecipeTest.java
  backend/src/test/java/org/youcancook/gobong/domain/recipe/service/RecipeServiceTest.java
Labels: 기능구현 🛫

#16 feat: 로그인 로직 구현
  backend/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/authentication/entity/RefreshToken.java
  backend/src/main/java/org/youcancook/gobong/domain/authentication/repository/RefreshTokenRepository.java
  backend/src/main/java/org/youcancook/gobong/domain/user/dto/response/LoginResponse.java
  backend/src/main/java/org/youcancook/gobong/domain/user/entity/OAuthProvider.java
  backend/src/main/java/org/youcancook/gobong/domain/user/exception/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/user/exception/OAuthProviderNotFoundException.java
  backend/src/main/java/org/youcancook/gobong/domain/user/repository/UserRepository.java
  backend/src/main/java/org/youcancook/gobong/domain/user/service/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/user/service/UserLoginService.java
  backend/src/main/java/org/youcancook/gobong/global/error/ErrorCode.java
  backend/src/main/java/org/youcancook/gobong/global/util/token/TokenDto.java
  backend/src/main/java/org/youcancook/gobong/global/util/token/TokenManager.java
  backend/src/test/java/org/youcancook/gobong/domain/user/service/UserLoginServiceTest.java
Labels: 기능구현 🛫

#15 feat: 단계별 레시피 추가 및 업데이트 기능 구현
  backend/src/main/java/org/youcancook/gobong/domain/recipe/entity/Recipe.java
  backend/src/main/java/org/youcancook/gobong/domain/recipedetail/dto/response/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/recipedetail/dto/response/UploadRecipeDetailResponse.java
  backend/src/main/java/org/youcancook/gobong/domain/recipedetail/entity/RecipeDetail.java
  backend/src/main/java/org/youcancook/gobong/domain/recipedetail/exception/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/recipedetail/repository/RecipeDetailRepository.java
  backend/src/main/java/org/youcancook/gobong/domain/recipedetail/service/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/recipedetail/service/RecipeDetailService.java
  backend/src/test/java/org/youcancook/gobong/domain/recipe/entity/RecipeTest.java
  backend/src/test/java/org/youcancook/gobong/domain/recipe/service/RecipeServiceTest.java
  backend/src/test/java/org/youcancook/gobong/domain/recipedetail/service/RecipeDetailServiceTest.java
Labels: 기능구현 🛫

#19 feat: AWS S3 이미지 업로드 구현
  backend/build.gradle
  backend/src/main/java/org/youcancook/gobong/global/error/ErrorCode.java
  backend/src/main/java/org/youcancook/gobong/global/util/s3/AwsS3ImageUploader.java
  backend/src/main/java/org/youcancook/gobong/global/util/s3/FileUploadException.java
  backend/src/main/java/org/youcancook/gobong/global/util/s3/S3Config.java
  backend/src/main/resources/application.yml
Labels: 기능구현 🛫

#17 feat: 로그인 컨트롤러 구현
  backend/src/main/java/org/youcancook/gobong/domain/authentication/exception/TemporaryTokenNotFoundException.java
  backend/src/main/java/org/youcancook/gobong/domain/authentication/repository/TemporaryTokenRepository.java
  backend/src/main/java/org/youcancook/gobong/domain/authentication/service/TemporaryTokenService.java
  backend/src/main/java/org/youcancook/gobong/domain/user/controller/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/user/controller/UserController.java
  backend/src/main/java/org/youcancook/gobong/domain/user/dto/request/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/user/dto/request/LoginRequest.java
  backend/src/main/java/org/youcancook/gobong/domain/user/dto/response/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/user/dto/response/TemporaryTokenIssueResponse.java
  backend/src/main/java/org/youcancook/gobong/global/util/token/TokenDto.java
  backend/src/test/java/org/youcancook/gobong/domain/authentication/service/TemporaryTokenServiceTest.java
  backend/src/test/java/org/youcancook/gobong/domain/user/controller/UserControllerTest.java
Labels: 기능구현 🛫, API 수정 👀

#21 feat: Argument Resolver 추가
  backend/src/main/java/org/youcancook/gobong/global/config/WebConfig.java
  backend/src/main/java/org/youcancook/gobong/global/error/ErrorCode.java
  backend/src/main/java/org/youcancook/gobong/global/resolver/.gitkeep
  backend/src/main/java/org/youcancook/gobong/global/resolver/LoginUserId.java
  backend/src/main/java/org/youcancook/gobong/global/resolver/LoginUserIdArgumentResolver.java
  backend/src/main/java/org/youcancook/gobong/global/util/token/TokenManager.java
  backend/src/main/java/org/youcancook/gobong/global/util/token/exception/EmptyAuthorizationException.java
  backend/src/main/java/org/youcancook/gobong/global/util/token/exception/ExpiredTokenException.java
  backend/src/main/java/org/youcancook/gobong/global/util/token/exception/InvalidTokenException.java
  backend/src/main/java/org/youcancook/gobong/global/util/token/exception/InvalidTokenTypeException.java
  backend/src/main/java/org/youcancook/gobong/global/util/token/exception/NotBearerGrantTypeException.java
  backend/src/test/java/org/youcancook/gobong/global/util/token/TokenManagerTest.java
Labels: 기능구현 🛫

#23 feat: 인수 테스트 격리 템플릿 추가
  backend/build.gradle
  backend/src/test/java/org/youcancook/gobong/global/util/acceptance/AcceptanceTest.java
  backend/src/test/java/org/youcancook/gobong/global/util/acceptance/DatabaseCleanup.java
Labels: 기능구현 🛫

#22 feat: 회원가입 컨트롤러 생성
  backend/src/main/java/org/youcancook/gobong/domain/authentication/service/TemporaryTokenService.java
  backend/src/main/java/org/youcancook/gobong/domain/user/controller/UserController.java
  backend/src/main/java/org/youcancook/gobong/domain/user/dto/SignupDto.java
  backend/src/main/java/org/youcancook/gobong/domain/user/dto/request/SignupRequest.java
  backend/src/main/java/org/youcancook/gobong/domain/user/entity/User.java
  backend/src/main/java/org/youcancook/gobong/domain/user/service/UserSignupService.java
  backend/src/main/java/org/youcancook/gobong/global/validation/.gitkeep
  backend/src/main/java/org/youcancook/gobong/global/validation/annotation/UserNickname.java
  backend/src/main/java/org/youcancook/gobong/global/validation/validator/UserNicknameValidator.java
  backend/src/test/java/org/youcancook/gobong/domain/authentication/service/TemporaryTokenServiceTest.java
  backend/src/test/java/org/youcancook/gobong/domain/user/controller/UserControllerTest.java
Labels: 기능구현 🛫, API 수정 👀

#24 feat: 레시피 삭제 기능 구현
  backend/src/main/java/org/youcancook/gobong/domain/bookmarkrecipe/repository/BookmarkRecipeRepository.java
  backend/src/main/java/org/youcancook/gobong/domain/rating/repository/RatingRepository.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/service/RecipeService.java
  backend/src/test/java/org/youcancook/gobong/domain/recipe/service/RecipeServiceTest.java
Labels: 기능구현 🛫

#27 feat: 팔로우 서비스 및 컨트롤러 구현
  backend/src/main/java/org/youcancook/gobong/domain/follow/controller/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/follow/controller/FollowController.java
  backend/src/main/java/org/youcancook/gobong/domain/follow/entity/Follow.java
  backend/src/main/java/org/youcancook/gobong/domain/follow/exception/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/follow/exception/AlreadyFollowingException.java
  backend/src/main/java/org/youcancook/gobong/domain/follow/exception/NotFollowingException.java
  backend/src/main/java/org/youcancook/gobong/domain/follow/repository/FollowRepository.java
  backend/src/main/java/org/youcancook/gobong/domain/follow/service/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/follow/service/FollowService.java
  backend/src/main/java/org/youcancook/gobong/domain/user/entity/User.java
  backend/src/main/java/org/youcancook/gobong/global/error/ErrorCode.java
  backend/src/test/java/org/youcancook/gobong/domain/follow/controller/FollowControllerTest.java
  backend/src/test/java/org/youcancook/gobong/domain/follow/service/FollowServiceTest.java
Labels: 기능구현 🛫, API 추가/수정 👀

#28 fix: 인수 테스트 격리에서 발생하는 테스트 실패 해결
  backend/src/main/java/org/youcancook/gobong/domain/authentication/entity/RefreshToken.java
  backend/src/main/java/org/youcancook/gobong/domain/authentication/entity/TemporaryToken.java
  backend/src/main/java/org/youcancook/gobong/domain/bookmarkrecipe/entity/BookmarkRecipe.java
  backend/src/main/java/org/youcancook/gobong/domain/follow/entity/Follow.java
  backend/src/main/java/org/youcancook/gobong/domain/rating/entity/Rating.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/entity/Recipe.java
  backend/src/main/java/org/youcancook/gobong/domain/recipedetail/entity/RecipeDetail.java
  backend/src/main/java/org/youcancook/gobong/domain/user/dto/response/TemporaryTokenIssueResponse.java
  backend/src/main/java/org/youcancook/gobong/domain/user/entity/User.java
  backend/src/main/resources/application.yml
  backend/src/test/java/org/youcancook/gobong/domain/bookmarkrecipe/service/BookmarkRecipeServiceTest.java
  backend/src/test/java/org/youcancook/gobong/domain/rating/service/RatingServiceTest.java
  backend/src/test/java/org/youcancook/gobong/domain/recipe/service/RecipeServiceTest.java
  backend/src/test/java/org/youcancook/gobong/domain/recipedetail/service/RecipeDetailServiceTest.java
  backend/src/test/java/org/youcancook/gobong/global/util/acceptance/AcceptanceTest.java
  backend/src/test/java/org/youcancook/gobong/global/util/service/DatabaseCleaner.java
  backend/src/test/java/org/youcancook/gobong/global/util/service/DatabaseCleanupExtension.java
  backend/src/test/java/org/youcancook/gobong/global/util/service/ServiceTest.java
Labels: 리팩터링 🛠, 사소한 버그 🙄

#30 feat: 레시피 컨트롤러 구현, 인수 테스트 작성
  backend/src/main/java/org/youcancook/gobong/domain/recipe/controller/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/recipe/controller/RecipeController.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/dto/response/CreateRecipeResponse.java
  backend/src/test/java/org/youcancook/gobong/domain/recipe/service/RecipeAcceptanceTest.java
  backend/src/test/java/org/youcancook/gobong/global/util/acceptance/AcceptanceUtils.java
Labels: 기능구현 🛫, API 추가/수정 👀

#31 feat: 북마크 컨트롤러 구현, 인수 테스트 작성
  backend/src/main/java/org/youcancook/gobong/domain/bookmarkrecipe/controller/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/bookmarkrecipe/controller/BookmarkRecipeController.java
  backend/src/test/java/org/youcancook/gobong/domain/bookmarkrecipe/service/BookmarkRecipeAcceptanceTest.java
Labels: 기능구현 🛫, API 추가/수정 👀

#32 fix: 회원가입 시에 oauthId와 provider가 이미 존재한 데이터인지 확인하는 검증 추가
  backend/src/main/java/org/youcancook/gobong/domain/user/dto/SignupDto.java
  backend/src/main/java/org/youcancook/gobong/domain/user/entity/User.java
  backend/src/main/java/org/youcancook/gobong/domain/user/exception/UserAlreadyExistsException.java
  backend/src/main/java/org/youcancook/gobong/domain/user/repository/UserRepository.java
  backend/src/main/java/org/youcancook/gobong/domain/user/service/UserSignupService.java
  backend/src/main/java/org/youcancook/gobong/global/error/ErrorCode.java
  backend/src/test/java/org/youcancook/gobong/domain/user/controller/UserControllerTest.java
  backend/src/test/java/org/youcancook/gobong/domain/user/service/UserSignupServiceTest.java
Labels: 사소한 버그 🙄

#34 fix: Basetime 타임스탬프가 데이터베이스에 기록되지 않던 버그 수정
  backend/src/main/java/org/youcancook/gobong/GobongApplication.java
  backend/src/test/java/org/youcancook/gobong/domain/BaseTime/BaseTimeTest.java
Labels: 심각한 버그 🐛

#36 feat: 이미지 업로드 컨트롤러 작성
  backend/build.gradle
  backend/src/main/java/org/youcancook/gobong/global/util/s3/AwsS3Controller.java
  backend/src/main/java/org/youcancook/gobong/global/util/s3/AwsS3ImageUploadResponse.java
  backend/src/main/java/org/youcancook/gobong/global/util/s3/AwsS3ImageUploader.java
  backend/src/test/java/org/youcancook/gobong/global/util/s3/AwsS3ImageUploaderTest.java
  backend/src/test/resources/testimage.png
Labels: 기능구현 🛫, API 추가/수정 👀

#40 feat: 리프레시 토큰 재발급 API
  backend/src/main/java/org/youcancook/gobong/domain/authentication/controller/AuthenticationController.java
  backend/src/main/java/org/youcancook/gobong/domain/authentication/dto/request/ReissueTokenRequest.java
  backend/src/main/java/org/youcancook/gobong/domain/authentication/dto/response/ReissueTokenResponse.java
  backend/src/main/java/org/youcancook/gobong/domain/authentication/exception/InvalidRefreshTokenException.java
  backend/src/main/java/org/youcancook/gobong/domain/authentication/exception/RefreshTokenNotFoundException.java
  backend/src/main/java/org/youcancook/gobong/domain/authentication/repository/RefreshTokenRepository.java
  backend/src/main/java/org/youcancook/gobong/domain/authentication/service/RefreshTokenService.java
  backend/src/main/java/org/youcancook/gobong/global/error/ErrorCode.java
  backend/src/test/java/org/youcancook/gobong/domain/authentication/controller/AuthenticationControllerTest.java
  backend/src/test/java/org/youcancook/gobong/domain/authentication/service/RefreshTokenServiceTest.java
Labels: 기능구현 🛫, API 추가/수정 👀

#33 feat: 팔로우, 팔로잉 API 생성
  backend/src/main/java/org/youcancook/gobong/domain/follow/controller/FollowController.java
  backend/src/main/java/org/youcancook/gobong/domain/follow/dto/response/.gitkeep
  backend/src/main/java/org/youcancook/gobong/domain/follow/dto/response/FindFolloweeResponse.java
  backend/src/main/java/org/youcancook/gobong/domain/follow/dto/response/FindFollowerResponse.java
  backend/src/main/java/org/youcancook/gobong/domain/follow/repository/FollowRepository.java
  backend/src/main/java/org/youcancook/gobong/domain/follow/service/FollowService.java
  backend/src/test/java/org/youcancook/gobong/domain/follow/controller/FollowControllerTest.java
Labels: 기능구현 🛫, API 추가/수정 👀

#41 feat: 레시피 단건 조회 구현
  backend/src/main/java/org/youcancook/gobong/domain/bookmarkrecipe/entity/BookmarkRecipe.java
  backend/src/main/java/org/youcancook/gobong/domain/bookmarkrecipe/service/BookmarkRecipeService.java
  backend/src/main/java/org/youcancook/gobong/domain/follow/service/FollowService.java
  backend/src/main/java/org/youcancook/gobong/domain/rating/entity/Rating.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/controller/RecipeController.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/dto/recipeDto/RecipeDto.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/dto/request/CreateRecipeRequest.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/dto/response/GetRecipeResponse.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/dto/response/GetRecipeSummaryResponse.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/dto/response/RecipeAuthorResponse.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/entity/Cookware.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/entity/Recipe.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/repository/RecipeRepository.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/service/GetRecipeService.java
  backend/src/main/java/org/youcancook/gobong/domain/recipedetail/dto/response/GetRecipeDetailResponse.java
  backend/src/main/java/org/youcancook/gobong/domain/recipedetail/repository/RecipeDetailRepository.java
  backend/src/main/java/org/youcancook/gobong/domain/recipedetail/service/RecipeDetailService.java
  backend/src/test/java/org/youcancook/gobong/domain/bookmarkrecipe/service/BookmarkRecipeServiceTest.java
  backend/src/test/java/org/youcancook/gobong/domain/follow/service/FollowServiceTest.java
  backend/src/test/java/org/youcancook/gobong/domain/rating/service/RatingServiceTest.java
  backend/src/test/java/org/youcancook/gobong/domain/recipe/entity/CookwareTest.java
  backend/src/test/java/org/youcancook/gobong/domain/recipe/service/RecipeAcceptanceTest.java
  backend/src/test/java/org/youcancook/gobong/domain/recipedetail/service/RecipeDetailServiceTest.java
Labels: 기능구현 🛫, API 추가/수정 👀

#42 feat: 문자열 배열을 조리도구 비트 수로 변환 기능 추가, Request에서 문자열 배열을 받도록 기능 구현
  backend/src/main/java/org/youcancook/gobong/domain/follow/service/FollowService.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/entity/Cookware.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/exception/IllegalCookwareException.java
  backend/src/main/java/org/youcancook/gobong/domain/recipedetail/dto/request/UploadRecipeDetailRequest.java
  backend/src/main/java/org/youcancook/gobong/domain/recipedetail/service/RecipeDetailService.java
  backend/src/main/java/org/youcancook/gobong/global/error/ErrorCode.java
  backend/src/test/java/org/youcancook/gobong/domain/bookmarkrecipe/service/BookmarkRecipeAcceptanceTest.java
  backend/src/test/java/org/youcancook/gobong/domain/recipe/entity/CookwareTest.java
  backend/src/test/java/org/youcancook/gobong/domain/recipe/service/RecipeAcceptanceTest.java
  backend/src/test/java/org/youcancook/gobong/domain/recipedetail/service/RecipeDetailServiceTest.java
Labels: 기능구현 🛫, API 추가/수정 👀

#43 feat: 유저 정보 조회, 닉네임과 프로필 사진 변경 api
  backend/src/main/java/org/youcancook/gobong/domain/user/controller/UserController.java
  backend/src/main/java/org/youcancook/gobong/domain/user/dto/request/UpdateUserInformationRequest.java
  backend/src/main/java/org/youcancook/gobong/domain/user/dto/response/UserInformationResponse.java
  backend/src/main/java/org/youcancook/gobong/domain/user/entity/User.java
  backend/src/main/java/org/youcancook/gobong/domain/user/service/UserInformationService.java
  backend/src/test/java/org/youcancook/gobong/domain/user/controller/UserControllerTest.java
  backend/src/test/java/org/youcancook/gobong/domain/user/service/UserInformationServiceTest.java
Labels: 기능구현 🛫, API 추가/수정 👀

#44 feat: 레시피 피드 전체조회 구현
  backend/src/main/java/org/youcancook/gobong/domain/recipe/controller/FeedController.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/dto/response/GetFeedResponse.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/dto/response/GetRecipeSummaryResponse.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/repository/RecipeRepository.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/service/GetRecipeService.java
  backend/src/test/java/org/youcancook/gobong/domain/recipe/service/GetRecipeServiceTest.java
  backend/src/test/java/org/youcancook/gobong/domain/recipe/service/RecipeAcceptanceTest.java
Labels: 기능구현 🛫, API 추가/수정 👀

#45 feat: 북마크 피드 조회 구현
  backend/src/main/java/org/youcancook/gobong/domain/recipe/controller/FeedController.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/repository/RecipeRepository.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/service/GetRecipeService.java
  backend/src/test/java/org/youcancook/gobong/domain/recipe/service/GetRecipeServiceTest.java
  backend/src/test/java/org/youcancook/gobong/domain/recipe/service/RecipeAcceptanceTest.java
  backend/src/test/java/org/youcancook/gobong/global/util/acceptance/AcceptanceUtils.java
Labels: 기능구현 🛫, API 추가/수정 👀

#46 feat: 팔로우한 사람 레시피 피드 구현
  backend/src/main/java/org/youcancook/gobong/domain/recipe/controller/FeedController.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/repository/RecipeRepository.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/service/GetRecipeService.java
  backend/src/test/java/org/youcancook/gobong/domain/recipe/service/GetRecipeServiceTest.java
  backend/src/test/java/org/youcancook/gobong/domain/recipe/service/RecipeAcceptanceTest.java
  backend/src/test/java/org/youcancook/gobong/global/util/acceptance/AcceptanceUtils.java
Labels: 기능구현 🛫, API 추가/수정 👀

#47 fix: 불필요한 IOException 제거
  backend/src/main/java/org/youcancook/gobong/global/util/s3/AwsS3Controller.java
  backend/src/main/java/org/youcancook/gobong/global/util/s3/AwsS3ImageUploader.java
Labels: 리팩터링 🛠

#49 docs: MIT 라이센스 추가
  LICENSE
Labels: 문서 🧾

#48 refactor: 변수명 적절하게 변경 및 PathVariable 사용으로 RequestBody 수정
  backend/src/main/java/org/youcancook/gobong/domain/recipe/controller/RecipeController.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/dto/request/UpdateRecipeRequest.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/service/RecipeService.java
  backend/src/main/java/org/youcancook/gobong/domain/recipedetail/dto/request/UploadRecipeDetailRequest.java
  backend/src/main/java/org/youcancook/gobong/domain/recipedetail/service/RecipeDetailService.java
  backend/src/test/java/org/youcancook/gobong/domain/recipe/service/RecipeAcceptanceTest.java
  backend/src/test/java/org/youcancook/gobong/domain/recipe/service/RecipeServiceTest.java
Labels: 리팩터링 🛠

#51 fix: 팔로워/팔로잉 리스트 쿼리 조건 추가, 팔로워 조회 시 팔로잉 여부 데이터 추가
  backend/src/main/java/org/youcancook/gobong/domain/follow/dto/response/FindFollowerResponse.java
  backend/src/main/java/org/youcancook/gobong/domain/follow/repository/FollowRepository.java
  backend/src/main/java/org/youcancook/gobong/domain/follow/service/FollowService.java
  backend/src/test/java/org/youcancook/gobong/domain/follow/controller/FollowControllerTest.java
Labels: 기능구현 🛫, API 추가/수정 👀

#52 feat: 유저 정보 변경 시, 현재와 동일한 닉네임이면 중복 확인을 하지 않도록 수정
  backend/src/main/java/org/youcancook/gobong/domain/user/service/UserInformationService.java
  backend/src/test/java/org/youcancook/gobong/domain/user/service/UserInformationServiceTest.java
Labels: 기능구현 🛫

#53 chore: 도커 타임존 설정
  backend/docker-compose.yml
Labels: 인프라 🌎

#55 feat: GetRecipeResponse에 나의 평점 추가
  backend/src/main/java/org/youcancook/gobong/domain/recipe/dto/response/GetRecipeResponse.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/service/GetRecipeService.java
Labels: API 추가/수정 👀

#56 feat: myFeed API
  backend/src/main/java/org/youcancook/gobong/domain/recipe/controller/FeedController.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/repository/RecipeRepository.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/service/GetRecipeService.java
  backend/src/test/java/org/youcancook/gobong/domain/recipe/service/GetRecipeServiceTest.java
  backend/src/test/java/org/youcancook/gobong/domain/recipe/service/RecipeAcceptanceTest.java
Labels: 기능구현 🛫, API 추가/수정 👀

#57 feat: 유저 정보 조회 시, 팔로우/팔로잉 인원수와 작성한 레시피 개수도 포함해서 반환해주도록 변경
  backend/src/main/java/org/youcancook/gobong/domain/follow/repository/FollowRepository.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/repository/RecipeRepository.java
  backend/src/main/java/org/youcancook/gobong/domain/user/dto/response/UserInformationResponse.java
  backend/src/main/java/org/youcancook/gobong/domain/user/service/UserInformationService.java
  backend/src/test/java/org/youcancook/gobong/domain/user/service/UserInformationServiceTest.java
Labels: API 추가/수정 👀

#59 feat: 다른 유저 정보 조회 구현
  backend/src/main/java/org/youcancook/gobong/domain/user/controller/UserController.java
  backend/src/test/java/org/youcancook/gobong/domain/user/controller/UserControllerTest.java
Labels: 기능구현 🛫, API 추가/수정 👀

#60 feat: 다른 유저 피드 조회 구현
  backend/src/main/java/org/youcancook/gobong/domain/recipe/controller/FeedController.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/repository/RecipeRepository.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/service/GetRecipeService.java
  backend/src/test/java/org/youcancook/gobong/domain/recipe/service/GetRecipeServiceTest.java
  backend/src/test/java/org/youcancook/gobong/domain/recipe/service/RecipeAcceptanceTest.java
Labels: 기능구현 🛫, API 추가/수정 👀

#62 fix: PageRequest의 인자 순서 바뀐 버그 수정
  backend/src/main/java/org/youcancook/gobong/domain/recipe/controller/FeedController.java
  backend/src/main/java/org/youcancook/gobong/domain/recipe/dto/feedfilterdto/ModifiedFeedFilterDto.java
  backend/src/test/java/org/youcancook/gobong/domain/recipe/service/RecipeAcceptanceTest.java
Labels: 심각한 버그 🐛

#63 fix: 필터링 쿼리가 null일 경우 빈 값으로 치환하도록 수정
  backend/src/main/java/org/youcancook/gobong/domain/recipe/dto/feedfilterdto/ModifiedFeedFilterDto.java
Labels: 사소한 버그 🙄

#13 docs: Readme 추가
  README.md
  readme.md
Labels: 문서 🧾
